### ISSUE TITLE
v1.0.0:SD_WU_3:When finished, file size should update: file size doesn't not get updated automatically

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#10]
Try to upload files in first_container to another folder. File size remains 0. Must refresh the page to get the size of file uploaded.

**Comment by jkim485** [comment]
Please ignore the description above: see the description in this comment:

Try to upload files in first_container. File size remains 0. Must refresh the folder view in order to get the size of file uploaded.

**Comment by jkim485** [comment]
tested on chrome 43.0.2357.130 m.

**Comment by jkim485** [comment]
Tested on scidrive 2: the issue has not been fixed.

**Comment by dimm0** [comment]
Fixed

**Comment by jkim485** [comment]
Tested and confirmed the fix.
