### ISSUE TITLE
v1.0.0:SD_WU_4: after moving files from one folder to another the file lists of  affected folders to not get updated automatically.

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#14]
the file lists of affected folders doesn't get updated unless  user goes to the root folder and  goes back the folders where files are moved from/to.

**Comment by jkim485** [comment]
tested on chrome 43.0.2357.130 m.

**Comment by dimm0** [comment]
Fixed

**Comment by jkim485** [comment]
Tested and confirmed the fix
