### ISSUE TITLE
Link to CASJobs URL is incorrect.

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#28]
When clicking the CasJobs icon, it opens the wrong URL (http://skyserver.sdss.org/casjobs/login.aspx) instead of the one on SciTest02.

**Comment by jkim485** [comment]
Tested on scidrive 2:
Still opens the wrong URL as described above.

**Comment by dimm0** [comment]
Is that button needed?

**Comment by jkim485** [comment]
Mike please answer it.

**Comment by mikear69** [comment]
No it is not.  Please remove it.
