### ISSUE TITLE
Multiple files upload

### ISSUE THREAD

**Issue by dimm0** [idies/scidrive-ui#3]
After about 200 files uploaded, I started to get "Can't upload File" and then a "Permission to create dialog" popup then another error popup that had a check box that told me I could skip getting this popup for all other errors. It was weird because I expected that the upload would be incomplete. But al 268 files I drag and dropped were "there". I haven't downloaded them back to my desktop to MD5 them to check that they correctly went up/down.

**Comment by raddick** [comment]
Is this still a problem as of today (6/26/2015)?

**Comment by dimm0** [comment]
Nope, fixed
