### ISSUE TITLE
When Dragging files onto SciDrive from Explorer, View does not update unless its one of the files registered for a Plugin.

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#32]
When Dragging files onto SciDrive from Explorer, View does not update unless its one of the files registered for a Plugin - HOWEVER, the Plugin does not seem like it needs to be active.

**Comment by jkim485** [comment]
Tested on scidrive 2:

When Dragging files onto SciDrive from Explorer, View does get update regardless of whether a file is one of the files registered for a Plugin (tested for both plugin is on/off): Still file size doesn't get update.

**Comment by dimm0** [comment]
Fixed

**Comment by jkim485** [comment]
Tested and confirmed the fix.
