### ISSUE TITLE
SD_WU_4: moving multiple PDF files from one folder to another in SciDrive: Folder view doesnot  get refreshed automaticallySD_WU_4: moving multiple PDF files from one folder to another in SciDrive: Folder view is not refreshed automatically at all.

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#35]
moved file names do not appear at all. Users must click refresh button.

**Comment by jkim485** [comment]
Tested on scidrive 2:
1. Folder view does not get refreshed automatically- still doesn't work
2 moving multiple PDF files from one folder to another in scidrive: cannot move the selected files at all.

**Comment by dimm0** [comment]
Fixed

**Comment by jkim485** [comment]
Tested and confirmed the fix.
