### ISSUE TITLE
Metadata extraction error: initial database set up failed

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive-ui#41]
Does anybody know what should be "endpoint" of metadata extractors to  CasJobs/MyDB on SciDrive? I have said to http://scitest02.pha.jhu.edu/CasJobs/RestApi and when i tried metadata extraction on a fits file, I got the following error message:
Metadata extraction status: done
Modified: Tue, 20 Oct 2015 11:49:09 -0400
Metadata extraction error: Initial database setup failed

**Comment by dmedv** [comment]
It should be http://scitest02.pha.jhu.edu/CasJobs

**Comment by jkim485** [comment]
Thank you. That worked.
